# Numpy( Numerical Python) library is used for efficient numerical computation
* Any new library needs to be installed first. 
    * Open Anaconda powershell prompt. 
    * Activate the desired environment. 'conda activate GSITI_ML'
    * Type 'conda install numpy' or 'pip install numpy'
* Numpy library has many built-in functions that make life easy
* Numpy is faster than usual Python math library
* Computations are efficient especially with lists (called numpy arrays)

In [2]:
#We first import the Numpy library and give it a nickname 'np'
import numpy as np

In [44]:
# Define a numpy array of length 5 with all entries=0
A=np.zeros([5])
print(A)

[0. 0. 0. 0. 0.]


In [46]:
# Assigning new entries
A[1]=10
A[3]=-20
print(A)

[  0.  10.   0. -20.   0.]


In [59]:
# Declaring an array of length 10
A=np.array([4,-7,18,1,21,-15,9,0,33,24])
print(A)

[  4  -7  18   1  21 -15   9   0  33  24]


In [60]:
# Check length
len(A)

10

In [61]:
# Getting n-th element
print(A[0])

4


In [62]:
print(A[5])

-15


In [63]:
#printing from 2nd element to 7th element
A[2:8]

array([ 18,   1,  21, -15,   9,   0])

In [64]:
#Extracting first 5 elements
A[0:5]

array([ 4, -7, 18,  1, 21])

In [68]:
# Extracting last 4 elements
A[-4:]

array([ 9,  0, 33, 24])

In [ ]:
B=np.array([6,7,8,9,10])
C=A+B
print(C)

In [9]:
D=C**2
print(C**2)

[ 49  81 121 169 225]


In [10]:
E=np.sqrt(C**2)
print(E)

[ 7.  9. 11. 13. 15.]


# Basic Statistics using numpy

In [27]:
X = [30, 70, 20, 140, 40, 90, 30, 110, 50]
print(X)

[30, 70, 20, 140, 40, 90, 30, 110, 50]


In [28]:
# Finding Minimum
X_min=np.min(X)
print(X_min)

20


In [29]:
# Maximum
print(np.max(X))

140


In [70]:
# Locating the array index where maximum occurs
max_loc=np.argmax(X)
print(max_loc)

3


In [30]:
# Average
X_av=np.mean(X)
print(X_av)

64.44444444444444


In [69]:
# Standard Deviation
np.std(X)

38.90475866669244

# Numpy 2-Dimensional Array
* Array indices start at 0,0
* For a 3X3 array following would be the arrangement

In [32]:
# Declaring an array of dimension(3x3) rows=3, columns=3
#         Col0--------Col1-------Col2
# Row0   (0,0)--------(0,1)--------(0,2)
#          |             |           |
#          |             |           |
# Row1   (1,0)--------(1,1)--------(1,2) 
#          |             |           |
#          |             |           |
# Row2   (2,0)--------(2,1)--------(2,2)


In [72]:
A=np.zeros([3,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
A[0,0]=1
A[0,1]=0
A[0,2]=4
print(A)

[[1. 0. 4.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [84]:
A[1,0]=3
A[1,1]=7
A[1,2]=10
A[2,0]=-4
A[2,1]=5
A[2,2]=8
print(A)

[[ 1.  0.  4.]
 [ 3.  7. 10.]
 [-4.  5.  8.]]


In [87]:
A.shape

(3, 3)

In [75]:
np.mean(A)

3.7777777777777777

In [76]:
# Extracting n-th row with all columns; Syntax A[n,:]. It means that "Get n-th row and ':'  implies 'with all columns'" 
print(A[0,:]) # Gets 0-th row

[1. 0. 4.]


In [90]:
# 2nd column with all rows
A[:, 2] # Gets 2-nd column

array([ 4., 10.,  8.])

In [94]:
# Minimum and locating the index of maxima
min=np.min(A)
(min_r, min_c)=np.unravel_index(A.argmin(), A.shape)
print('Minimum of array A is: ', min)
print('Location of minima is: ', min_r, ',', min_c)

Minimum of array A is:  -4.0
Location of minima is:  2 , 0
